services:
  app:
    build: .
    container_name: musiclabel_apache
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      APP_ENV: production
      DB_HOST: db
      DB_DATABASE: mydb
      DB_USERNAME: myuser
      DB_PASSWORD: mypass
    networks:
      - musiclabel_net 

    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro # persist the certificate between docker rebuilds

  db:
    image: mysql:8.0
    container_name: musiclabel_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - musiclabel_net

networks:
  musiclabel_net:

volumes:
  db_data:
